### ISSUE TITLE
`nil` is not a valid state for `dispatch!` not `dispatch-sync!`

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/citrus#20]
Hello, long time no bug report :smile: 

I noticed a small problem/inconsistency. When I `dispatch!` an event that's supposed to clear the current state by setting it to `nil`, the state isn't cleared at all. In fact it isn't changed.

Some code to show the problem :

``` clojure
(defmutli widget-controller (fn [event _ _ ] event))

(defmethod widget-controller :clear [_ _ _]
  {:state nil})
```

The problem comes from [the Reconciler](https://github.com/roman01la/citrus/blob/a71d740536ed0e02774873712ff5d6a75be29ce4/src/citrus/reconciler.cljs#L75). The line `(let [state-effects (filter (comp :state second) effects) ;; other bindings])` will prevent state declared with `nil` as a target value to be taken into account. Indeed, in the REPL :

``` clojure
(filter :a [{:a 1} {:a 2} {:a nil}])
;; => ({:a 1} {:a 2})
```

The problem doesn't happen if I `dispatch-sync!` instead. I think `dispatch-sync!` has the right behavior. `nil` is a totally valid value for piece of state.

Here's a solution, directly taken from the code of the binding for `other-effects` (just below the code linked above). First bad code example, second is solution :

``` clojure
;; Bad, current code
(let [effects [[:ctrl1 {:state 1 :some :effect}]
               [:ctrl2 {:state nil}]
               [:ctrl3 {:some :effect}]]] 
  (filter (comp :state second) effects))
;; => ([:ctrl1 {:state 1, :some :effect}]) ;; :ctrl2 has been filtered out ! Furthermore, the effects are still here (it's ok they're filtered just after though)

;; Good, solution proposed
(let [effects [[:ctrl1 {:state 1 :some :effect}]
               [:ctrl2 {:state nil}]
               [:ctrl3 {:some :effect}]]]
  (->> effects
       (map (fn [[cname effect]]
              [cname (select-keys effect [:state])]))
       (filter (comp seq second))))
;; => ([:ctrl1 {:state 1}] [:ctrl2 {:state nil}]) ;; :ctrl2 still here and only :state effects \o/
```

Note : I'm still using `[org.roman01la/scrum "2.1.0-SNAPSHOT" :exclusions [rum]]` but I'm not asking you to fix this old version. I'll move to citrus soon.

In the meantime, I'll just put an empty map when `:clear`ing state.

End of bug report. Have a nice day !

**Comment by roman01la** [comment]
As always, I'm happy to merge a PR 😃

**Comment by roman01la** [comment]
I just published `3.0.1`, not sure but it probably solves your problem. Give it a try and let me know.

**Comment by DjebbZ** [comment]
Updated to `3.0.1`, problem still remains. Maybe it's a problem from our code base, I'll double check. I'll still work on the PR #22 anyway.

**Comment by roman01la** [comment]
@DjebbZ Hey! Do you still have that problem?

**Comment by DjebbZ** [comment]
Yes. Maybe when #22 is done, the bug will be magically solved.

**Comment by DjebbZ** [comment]
Closing since it's solved on master.
